# Generated by Django 5.0.1 on 2024-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishvocabulary',
            options={'verbose_name': 'Vocabulary', 'verbose_name_plural': 'List vocabulary'},
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='audio',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='englishvocabulary',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
