# Generated by Django 5.0.1 on 2024-01-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vocabulary', '0002_alter_englishvocabulary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishvocabulary',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
